### ISSUE TITLE
Create a simple app to fetch data asynchronously on form submit

### ISSUE THREAD

**Issue by 1Copenut** [1Copenut/react-bytes#2]
## Tasks
- [x] Use axios on another, to compare the two
- [x] Fire one async data call with a `submit` event
- [x] Use the data to create a visual, like a list or table (why not both?)

## Related Issues
#9

**Comment by 1Copenut** [comment]
Closing with commit [5c885fe](https://github.com/1Copenut/react-bytes/commit/5c885fe2e847af4474f903ab1b815a745d997df3)
